/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-04 at 01:46:07 UTC 
 * Modify at your own risk.
 */

package com.virtualef.pgj.service.commandmentService.model;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Model definition for CommandmentDto.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the commandmentService. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CommandmentDto extends com.google.api.client.json.GenericJson implements Parcelable{

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String address;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AgentDto agent;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String area;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> audio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String commandmentType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String court;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String crime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String date;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String department;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> evidence;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idAgent;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idRequire;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String inquest;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String judge;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float latitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float longitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String observations;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String order;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String record;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private RequireDto require;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean status;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAddress() {
    return address;
  }

  /**
   * @param address address or {@code null} for none
   */
  public CommandmentDto setAddress(java.lang.String address) {
    this.address = address;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public AgentDto getAgent() {
    return agent;
  }

  /**
   * @param agent agent or {@code null} for none
   */
  public CommandmentDto setAgent(AgentDto agent) {
    this.agent = agent;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getArea() {
    return area;
  }

  /**
   * @param area area or {@code null} for none
   */
  public CommandmentDto setArea(java.lang.String area) {
    this.area = area;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getAudio() {
    return audio;
  }

  /**
   * @param audio audio or {@code null} for none
   */
  public CommandmentDto setAudio(java.util.List<java.lang.String> audio) {
    this.audio = audio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCommandmentType() {
    return commandmentType;
  }

  /**
   * @param commandmentType commandmentType or {@code null} for none
   */
  public CommandmentDto setCommandmentType(java.lang.String commandmentType) {
    this.commandmentType = commandmentType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCourt() {
    return court;
  }

  /**
   * @param court court or {@code null} for none
   */
  public CommandmentDto setCourt(java.lang.String court) {
    this.court = court;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCrime() {
    return crime;
  }

  /**
   * @param crime crime or {@code null} for none
   */
  public CommandmentDto setCrime(java.lang.String crime) {
    this.crime = crime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDate() {
    return date;
  }

  /**
   * @param date date or {@code null} for none
   */
  public CommandmentDto setDate(java.lang.String date) {
    this.date = date;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDepartment() {
    return department;
  }

  /**
   * @param department department or {@code null} for none
   */
  public CommandmentDto setDepartment(java.lang.String department) {
    this.department = department;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getEvidence() {
    return evidence;
  }

  /**
   * @param evidence evidence or {@code null} for none
   */
  public CommandmentDto setEvidence(java.util.List<java.lang.String> evidence) {
    this.evidence = evidence;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public CommandmentDto setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdAgent() {
    return idAgent;
  }

  /**
   * @param idAgent idAgent or {@code null} for none
   */
  public CommandmentDto setIdAgent(java.lang.Long idAgent) {
    this.idAgent = idAgent;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdRequire() {
    return idRequire;
  }

  /**
   * @param idRequire idRequire or {@code null} for none
   */
  public CommandmentDto setIdRequire(java.lang.Long idRequire) {
    this.idRequire = idRequire;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getInquest() {
    return inquest;
  }

  /**
   * @param inquest inquest or {@code null} for none
   */
  public CommandmentDto setInquest(java.lang.String inquest) {
    this.inquest = inquest;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getJudge() {
    return judge;
  }

  /**
   * @param judge judge or {@code null} for none
   */
  public CommandmentDto setJudge(java.lang.String judge) {
    this.judge = judge;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLatitude() {
    return latitude;
  }

  /**
   * @param latitude latitude or {@code null} for none
   */
  public CommandmentDto setLatitude(java.lang.Float latitude) {
    this.latitude = latitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLongitude() {
    return longitude;
  }

  /**
   * @param longitude longitude or {@code null} for none
   */
  public CommandmentDto setLongitude(java.lang.Float longitude) {
    this.longitude = longitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getObservations() {
    return observations;
  }

  /**
   * @param observations observations or {@code null} for none
   */
  public CommandmentDto setObservations(java.lang.String observations) {
    this.observations = observations;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOrder() {
    return order;
  }

  /**
   * @param order order or {@code null} for none
   */
  public CommandmentDto setOrder(java.lang.String order) {
    this.order = order;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRecord() {
    return record;
  }

  /**
   * @param record record or {@code null} for none
   */
  public CommandmentDto setRecord(java.lang.String record) {
    this.record = record;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public RequireDto getRequire() {
    return require;
  }

  /**
   * @param require require or {@code null} for none
   */
  public CommandmentDto setRequire(RequireDto require) {
    this.require = require;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public CommandmentDto setStatus(java.lang.Boolean status) {
    this.status = status;
    return this;
  }

  @Override
  public CommandmentDto set(String fieldName, Object value) {
    return (CommandmentDto) super.set(fieldName, value);
  }

  @Override
  public CommandmentDto clone() {
    return (CommandmentDto) super.clone();
  }

@Override
public int describeContents() {
	// TODO Auto-generated method stub
	return 0;
}

@Override
public void writeToParcel(Parcel dest, int flags) {
	// TODO Auto-generated method stub
	
}

}
