/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-05-25 at 03:43:46 UTC 
 * Modify at your own risk.
 */

package com.virtualef.pgj.service.locationService;

/**
 * Service definition for LocationService (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link LocationServiceRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class LocationService extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the locationService library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://civic-athlete-851.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "locationService/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public LocationService(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  LocationService(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getLocations".
   *
   * This request holds the parameters needed by the locationService server.  After setting any
   * optional parameters, call the {@link GetLocations#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public GetLocations getLocations() throws java.io.IOException {
    GetLocations result = new GetLocations();
    initialize(result);
    return result;
  }

  public class GetLocations extends LocationServiceRequest<com.virtualef.pgj.service.locationService.model.CollectionResponseLocationDto> {

    private static final String REST_PATH = "locationdto";

    /**
     * Create a request for the method "getLocations".
     *
     * This request holds the parameters needed by the the locationService server.  After setting any
     * optional parameters, call the {@link GetLocations#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetLocations#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetLocations() {
      super(LocationService.this, "GET", REST_PATH, null, com.virtualef.pgj.service.locationService.model.CollectionResponseLocationDto.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetLocations setAlt(java.lang.String alt) {
      return (GetLocations) super.setAlt(alt);
    }

    @Override
    public GetLocations setFields(java.lang.String fields) {
      return (GetLocations) super.setFields(fields);
    }

    @Override
    public GetLocations setKey(java.lang.String key) {
      return (GetLocations) super.setKey(key);
    }

    @Override
    public GetLocations setOauthToken(java.lang.String oauthToken) {
      return (GetLocations) super.setOauthToken(oauthToken);
    }

    @Override
    public GetLocations setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetLocations) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetLocations setQuotaUser(java.lang.String quotaUser) {
      return (GetLocations) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetLocations setUserIp(java.lang.String userIp) {
      return (GetLocations) super.setUserIp(userIp);
    }

    @Override
    public GetLocations set(String parameterName, Object value) {
      return (GetLocations) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getLocationsByAgentId".
   *
   * This request holds the parameters needed by the locationService server.  After setting any
   * optional parameters, call the {@link GetLocationsByAgentId#execute()} method to invoke the remote
   * operation.
   *
   * @param idAgent
   * @return the request
   */
  public GetLocationsByAgentId getLocationsByAgentId(java.lang.Long idAgent) throws java.io.IOException {
    GetLocationsByAgentId result = new GetLocationsByAgentId(idAgent);
    initialize(result);
    return result;
  }

  public class GetLocationsByAgentId extends LocationServiceRequest<com.virtualef.pgj.service.locationService.model.CollectionResponseLocationDto> {

    private static final String REST_PATH = "locationdto/{idAgent}";

    /**
     * Create a request for the method "getLocationsByAgentId".
     *
     * This request holds the parameters needed by the the locationService server.  After setting any
     * optional parameters, call the {@link GetLocationsByAgentId#execute()} method to invoke the
     * remote operation. <p> {@link GetLocationsByAgentId#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param idAgent
     * @since 1.13
     */
    protected GetLocationsByAgentId(java.lang.Long idAgent) {
      super(LocationService.this, "GET", REST_PATH, null, com.virtualef.pgj.service.locationService.model.CollectionResponseLocationDto.class);
      this.idAgent = com.google.api.client.util.Preconditions.checkNotNull(idAgent, "Required parameter idAgent must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetLocationsByAgentId setAlt(java.lang.String alt) {
      return (GetLocationsByAgentId) super.setAlt(alt);
    }

    @Override
    public GetLocationsByAgentId setFields(java.lang.String fields) {
      return (GetLocationsByAgentId) super.setFields(fields);
    }

    @Override
    public GetLocationsByAgentId setKey(java.lang.String key) {
      return (GetLocationsByAgentId) super.setKey(key);
    }

    @Override
    public GetLocationsByAgentId setOauthToken(java.lang.String oauthToken) {
      return (GetLocationsByAgentId) super.setOauthToken(oauthToken);
    }

    @Override
    public GetLocationsByAgentId setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetLocationsByAgentId) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetLocationsByAgentId setQuotaUser(java.lang.String quotaUser) {
      return (GetLocationsByAgentId) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetLocationsByAgentId setUserIp(java.lang.String userIp) {
      return (GetLocationsByAgentId) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long idAgent;

    /**

     */
    public java.lang.Long getIdAgent() {
      return idAgent;
    }

    public GetLocationsByAgentId setIdAgent(java.lang.Long idAgent) {
      this.idAgent = idAgent;
      return this;
    }

    @Override
    public GetLocationsByAgentId set(String parameterName, Object value) {
      return (GetLocationsByAgentId) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertLocation".
   *
   * This request holds the parameters needed by the locationService server.  After setting any
   * optional parameters, call the {@link InsertLocation#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.virtualef.pgj.service.locationService.model.LocationDto}
   * @return the request
   */
  public InsertLocation insertLocation(com.virtualef.pgj.service.locationService.model.LocationDto content) throws java.io.IOException {
    InsertLocation result = new InsertLocation(content);
    initialize(result);
    return result;
  }

  public class InsertLocation extends LocationServiceRequest<com.virtualef.pgj.service.locationService.model.LocationDto> {

    private static final String REST_PATH = "locationdto";

    /**
     * Create a request for the method "insertLocation".
     *
     * This request holds the parameters needed by the the locationService server.  After setting any
     * optional parameters, call the {@link InsertLocation#execute()} method to invoke the remote
     * operation. <p> {@link InsertLocation#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.virtualef.pgj.service.locationService.model.LocationDto}
     * @since 1.13
     */
    protected InsertLocation(com.virtualef.pgj.service.locationService.model.LocationDto content) {
      super(LocationService.this, "POST", REST_PATH, content, com.virtualef.pgj.service.locationService.model.LocationDto.class);
    }

    @Override
    public InsertLocation setAlt(java.lang.String alt) {
      return (InsertLocation) super.setAlt(alt);
    }

    @Override
    public InsertLocation setFields(java.lang.String fields) {
      return (InsertLocation) super.setFields(fields);
    }

    @Override
    public InsertLocation setKey(java.lang.String key) {
      return (InsertLocation) super.setKey(key);
    }

    @Override
    public InsertLocation setOauthToken(java.lang.String oauthToken) {
      return (InsertLocation) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertLocation setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertLocation) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertLocation setQuotaUser(java.lang.String quotaUser) {
      return (InsertLocation) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertLocation setUserIp(java.lang.String userIp) {
      return (InsertLocation) super.setUserIp(userIp);
    }

    @Override
    public InsertLocation set(String parameterName, Object value) {
      return (InsertLocation) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeLocation".
   *
   * This request holds the parameters needed by the locationService server.  After setting any
   * optional parameters, call the {@link RemoveLocation#execute()} method to invoke the remote
   * operation.
   *
   * @param idAgent
   * @return the request
   */
  public RemoveLocation removeLocation(java.lang.Long idAgent) throws java.io.IOException {
    RemoveLocation result = new RemoveLocation(idAgent);
    initialize(result);
    return result;
  }

  public class RemoveLocation extends LocationServiceRequest<Void> {

    private static final String REST_PATH = "locationdto/{id}";

    /**
     * Create a request for the method "removeLocation".
     *
     * This request holds the parameters needed by the the locationService server.  After setting any
     * optional parameters, call the {@link RemoveLocation#execute()} method to invoke the remote
     * operation. <p> {@link RemoveLocation#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param idAgent
     * @since 1.13
     */
    protected RemoveLocation(java.lang.Long idAgent) {
      super(LocationService.this, "DELETE", REST_PATH, null, Void.class);
      this.idAgent = com.google.api.client.util.Preconditions.checkNotNull(idAgent, "Required parameter idAgent must be specified.");
    }

    @Override
    public RemoveLocation setAlt(java.lang.String alt) {
      return (RemoveLocation) super.setAlt(alt);
    }

    @Override
    public RemoveLocation setFields(java.lang.String fields) {
      return (RemoveLocation) super.setFields(fields);
    }

    @Override
    public RemoveLocation setKey(java.lang.String key) {
      return (RemoveLocation) super.setKey(key);
    }

    @Override
    public RemoveLocation setOauthToken(java.lang.String oauthToken) {
      return (RemoveLocation) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveLocation setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveLocation) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveLocation setQuotaUser(java.lang.String quotaUser) {
      return (RemoveLocation) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveLocation setUserIp(java.lang.String userIp) {
      return (RemoveLocation) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long idAgent;

    /**

     */
    public java.lang.Long getIdAgent() {
      return idAgent;
    }

    public RemoveLocation setIdAgent(java.lang.Long idAgent) {
      this.idAgent = idAgent;
      return this;
    }

    @Override
    public RemoveLocation set(String parameterName, Object value) {
      return (RemoveLocation) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateLocation".
   *
   * This request holds the parameters needed by the locationService server.  After setting any
   * optional parameters, call the {@link UpdateLocation#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.virtualef.pgj.service.locationService.model.LocationDto}
   * @return the request
   */
  public UpdateLocation updateLocation(com.virtualef.pgj.service.locationService.model.LocationDto content) throws java.io.IOException {
    UpdateLocation result = new UpdateLocation(content);
    initialize(result);
    return result;
  }

  public class UpdateLocation extends LocationServiceRequest<com.virtualef.pgj.service.locationService.model.LocationDto> {

    private static final String REST_PATH = "locationdto";

    /**
     * Create a request for the method "updateLocation".
     *
     * This request holds the parameters needed by the the locationService server.  After setting any
     * optional parameters, call the {@link UpdateLocation#execute()} method to invoke the remote
     * operation. <p> {@link UpdateLocation#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.virtualef.pgj.service.locationService.model.LocationDto}
     * @since 1.13
     */
    protected UpdateLocation(com.virtualef.pgj.service.locationService.model.LocationDto content) {
      super(LocationService.this, "PUT", REST_PATH, content, com.virtualef.pgj.service.locationService.model.LocationDto.class);
    }

    @Override
    public UpdateLocation setAlt(java.lang.String alt) {
      return (UpdateLocation) super.setAlt(alt);
    }

    @Override
    public UpdateLocation setFields(java.lang.String fields) {
      return (UpdateLocation) super.setFields(fields);
    }

    @Override
    public UpdateLocation setKey(java.lang.String key) {
      return (UpdateLocation) super.setKey(key);
    }

    @Override
    public UpdateLocation setOauthToken(java.lang.String oauthToken) {
      return (UpdateLocation) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateLocation setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateLocation) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateLocation setQuotaUser(java.lang.String quotaUser) {
      return (UpdateLocation) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateLocation setUserIp(java.lang.String userIp) {
      return (UpdateLocation) super.setUserIp(userIp);
    }

    @Override
    public UpdateLocation set(String parameterName, Object value) {
      return (UpdateLocation) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link LocationService}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link LocationService}. */
    @Override
    public LocationService build() {
      return new LocationService(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link LocationServiceRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setLocationServiceRequestInitializer(
        LocationServiceRequestInitializer locationserviceRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(locationserviceRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
